CREATE TABLE IF NOT EXISTS tick_data (
    timestamp TIMESTAMP,
    instrument_key SYMBOL CAPACITY 512 CACHE,
    feed_type SYMBOL CAPACITY 256 CACHE,
    ltp DOUBLE,
    ltq LONG,
    cp DOUBLE,
    oi LONG,
    atp DOUBLE,
    vtt LONG,
    tbq DOUBLE,
    tsq DOUBLE,
    delta DOUBLE,
    theta DOUBLE,
    gamma DOUBLE,
    vega DOUBLE,
    rho DOUBLE,
    iv DOUBLE,
    bid_price_1 DOUBLE,
    bid_qty_1 LONG,
    ask_price_1 DOUBLE,
    ask_qty_1 LONG,
    open DOUBLE,
    high DOUBLE,
    low DOUBLE,
    close DOUBLE,
    insertion_time TIMESTAMP,
    processed_time TIMESTAMP
) timestamp(timestamp) PARTITION BY DAY WAL
WITH maxUncommittedRows=500000, o3MaxLag=600000000us;
